# site settings
title: The German Truth
subtitle: 2026 by Klaus Runge
email: runge.post@outlook.de
description: Meine Warheit, oder warum wir die Welt nicht retten können.
theme: null
markdown: kramdown

remote_theme: jekyll/minima # Falls Sie ein Theme nutzen, ansonsten weglassen
plugins:
  - jekyll-sitemap

url: "https://thegermantruth.github.io"
baseurl: "/TheGermanTruth"






